### PR TITLE
[ui] Add/Edit service chart values

### LINKED ISSUE #252: [ui] Add/Edit service chart values
- To flesh out, but the UI side of https://github.com/epinio/epinio/issues/1633
- It's expected these work in the same way as application chart values
```[tasklist]
### Tasks
- [ ] https://github.com/epinio/ui/issues/338
- [ ] https://github.com/epinio/ui/issues/339
- [ ] https://github.com/epinio/ui/issues/302
```

### LINKED ISSUE #296: [ui] Catalog Service is empty
**Setup**
- Epinio UI version: 1.9.0

**To Reproduce**

Go To Services -> Edit a Service

**Screenshots**

image

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes epinio/ui#252
Fixes epinio/ui#296

### Technical Notes
- How to create service chart settings for a Service Catalog: https://docs.epinio.io/howtos/create_custom_service#user-settable-configuration-values
- Epinio 1.9.0 supports only basic key-value `string` maps.
- Edit service chart values is not supported at the moment. The chart fields are disabled in edit mode.

### Screenshots

View:
image

Create:
image

Edit:
image

### CODE REVIEW

File: dashboard/pkg/epinio/edit/services.vue [hunk 1]
```diff
@@ -51,7 +55,7 @@ export default Vue.extend<Data, EpinioCompRecord, EpinioCompRecord, EpinioCompRe
       this.mixinFetch()
     ]);
 
-    Vue.set(this.value, 'catalog_service', this.$route.query[EPINIO_SERVICE_PARAM]);
+    Vue.set(this.value, 'catalog_service', this.selectedCatalogService?.meta.name || null);
```
Comment (richard-cox) [inline dashboard/pkg/epinio/edit/services.vue:58]: this breaks autopopulating the service when clicking on a service from the home page

File: dashboard/pkg/epinio/edit/services.vue [hunk 2]
```diff
@@ -75,6 +89,10 @@ export default Vue.extend<Data, EpinioCompRecord, EpinioCompRecord, EpinioCompRe
         return false;
       }
 
+      if (!Object.values(this.validChartValues).every((v) => !!v)) {
```
Comment (richard-cox) [inline dashboard/pkg/epinio/edit/services.vue:92]: just checking, is there no scenario where a falsey is allowed, for instance an empty string?

**Review by richard-cox — CHANGES_REQUESTED** [review]
in the shared epinio i've updated the `mysql-dev` service to include 
```  settings:
    "ingress.enabled":
      type: "bool"
    "ingress.hostname":
      type: "string"
```
- clicking the ingress.enabled checkbox doesn't check the box until text is entered in the `ingress.hostname` field
- when saving this the service failed to be created (could be that it expects the settings to correlate with helm variables?)
- the detail view (read only edit view) shows quotes for the text
  - image

**Comment by andreas-kupries** [comment]
> in the shared epinio i've updated the `mysql-dev` service to include
> 
> ```
>     "ingress.enabled":
>       type: "bool"
>     "ingress.hostname":
>       type: "string"
> ```
> 
>     * clicking the ingress.enabled checkbox doesn't check the box until text is entered in the `ingress.hostname` field
> 
>     * when saving this the service failed to be created (could be that it expects the settings to correlate with helm variables?)
>       
>       * Edit - this did eventually deploy. we might not be waiting long enough for the deployed state
> 
>     * the detail view (read only edit view) shows quotes for the text
>       
>       * image

Note https://deploy-preview-265--epinio-docs-staging.netlify.app/next/howtos/using_custom_service_values
documenting how the various forms in a charts values.yaml, a service's settings, and the -v options correlate.

Note especially the array and map support.

**Comment by torchiaf** [comment]
> * clicking the ingress.enabled checkbox doesn't check the box until text is entered in the `ingress.hostname` field

I could verify this bug on Service charts, applications chart work fine. Needs investigation

> * when saving this the service failed to be created (could be that it expects the settings to correlate with helm variables?)
>   * Edit - this did eventually deploy. we might not be waiting long enough for the deployed state

This is also happening testing `main` branch, I opened an issue for that: https://github.com/epinio/ui/issues/298

> * the detail view (read only edit view) shows quotes for the text
>   * image

The UI correctly sends string values without double quotes, then gets back service details with quoted strings:

- Request:
image

- Response:
image



It seems to be a regression, needs to double check with the be team and open an issue, in case.

**Comment by torchiaf** [comment]
> > in the shared epinio i've updated the `mysql-dev` service to include
> > ```
> >     "ingress.enabled":
> >       type: "bool"
> >     "ingress.hostname":
> >       type: "string"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > * clicking the ingress.enabled checkbox doesn't check the box until text is entered in the `ingress.hostname` field
> > 
> > * when saving this the service failed to be created (could be that it expects the settings to correlate with helm variables?)
> >   
> >   * Edit - this did eventually deploy. we might not be waiting long enough for the deployed state
> > 
> > * the detail view (read only edit view) shows quotes for the text
> >   
> >   * image
> > ```
> 
> Note https://deploy-preview-265--epinio-docs-staging.netlify.app/next/howtos/using_custom_service_values documenting how the various forms in a charts values.yaml, a service's settings, and the -v options correlate.
> 
> Note especially the array and map support.

I'm opening a new issue to support new array types.

File: dashboard/pkg/epinio/edit/services.vue (hunk 1 above)
Comment (torchiaf) [reply dashboard/pkg/epinio/edit/services.vue:58]: Fixed

File: dashboard/pkg/epinio/edit/services.vue (hunk 2 above)
Comment (torchiaf) [reply dashboard/pkg/epinio/edit/services.vue:92]: No scenarios, also checked Applications charts

**Comment by torchiaf** [comment]
Thanks @richard-cox , small issues from UI side are fixed. There are a few related pending issues :

- Timeout error when creating services with bound apps: https://github.com/epinio/ui/issues/298
- Support complex setting types: https://github.com/epinio/ui/issues/302
- Quoted strings: verified by backend, to open a new issue for be.
- Cannot edit services: https://github.com/epinio/ui/issues/303

File: dashboard/pkg/epinio/models/services.js [hunk 3]
```diff
@@ -94,4 +95,11 @@ export default class EpinioServiceModel extends EpinioNamespacedResource {
   bulkRemove(items, opt) {
     return bulkRemove(items, opt);
   }
+
+  async details() {
```
Comment (richard-cox) [inline dashboard/pkg/epinio/models/services.js:99]: this is just fetching the service resource?

if we need an update, it should be via `epinio/find` with an opt include `force: true`, then the latest version will be in the store

File: dashboard/pkg/epinio/edit/services.vue [hunk 4]
```diff
@@ -60,9 +64,19 @@ export default Vue.extend<Data, EpinioCompRecord, EpinioCompRecord, EpinioCompRe
...
       failedWaitingForDeploy: false,
       selectedApps:           this.value.boundapps || [],
+      chartValues:            {},
+      validChartValues:       {}
     };
   },
 
+  mounted() {
+    if (this.mode !== 'create') {
+      this.value.details().then((details: any) => {
```
Comment (richard-cox) [inline dashboard/pkg/epinio/edit/services.vue:74]: See comment for service model `details`. 

This will make a http request to fetch the service that we're already viewing. If the user refreshes on the page it'll be the second request to fetch the same service. 

If there are scenarios where the `settings` section is missing we should make the request optional given that scenario (and use epinio/find with force: true when fetching).

**Review by richard-cox — CHANGES_REQUESTED** [review]
there's some interesting things going on with the spec (added a comment to https://github.com/epinio/ui/issues/302#issuecomment-1677221052). those don't block this pr though

File: dashboard/pkg/epinio/models/services.js (hunk 3 above)
Comment (torchiaf) [reply dashboard/pkg/epinio/models/services.js]: Replaced with `store` function.

File: dashboard/pkg/epinio/edit/services.vue (hunk 4 above)
Comment (torchiaf) [reply dashboard/pkg/epinio/edit/services.vue]: Replaced with `store` function.

Comment (richard-cox) [reply dashboard/pkg/epinio/edit/services.vue]: There's still the issue of making an unneeded second request if the user refreshes on the view or edit service page.

image

Even when navigating here from the list page they will already have the resource.

How come we need to make this request, is there a scenario when information is missing?

**Review by richard-cox — CHANGES_REQUESTED** [review]
just one comment, then we're good

File: dashboard/pkg/epinio/edit/services.vue (hunk 4 above)
Comment (torchiaf) [reply dashboard/pkg/epinio/edit/services.vue]: Additional `find` request is done because the custom settings is provided only by `/namespaces/{Namespace}/services` GET request.
Request to add custom settings to the `services` list API: https://github.com/epinio/epinio/issues/2519

Comment (torchiaf) [reply dashboard/pkg/epinio/edit/services.vue]: @richard-cox we verified that the settings are correctly provided by `services` list api, and are provided by `CreateEditView` underneath componente: https://github.com/epinio/epinio/issues/2519#issuecomment-1686602901
Given that, I removed the extra request.

**Review by richard-cox — APPROVED** [review]
