### PR TITLE
Fix custom variables validation in Application edit mode

### LINKED ISSUE #299: [ui] Custom Variables are not validated in Application edit mode
**Setup**
- Epinio UI version: 1.9.0

**To Reproduce**

1- Edit an application having at least a custom variable with constraints (i.e. numeric variable with `min` value)
2- Set an invalid value. (i.e. min=5 value= 2)

**Result**
The Save button is enabled

**Expected Result**

Save button should be disabled.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by torchiaf**
### Summary
Fixes #299 

### Technical notes summary

- Disable 'Save' button when the custom settings are not valid
- Disable 'Update Source' when the custom settings in the Details tab are not valid.
- Show errors in Details tab's header.

### Screenshot/Video

In the example below, the validation failed because 'foo' field has a minimum value.

Button Disabled
image

Tab errors
image

### CODE REVIEW

File: dashboard/pkg/epinio/edit/applications.vue [hunk 1]
```diff
@@ -191,6 +192,13 @@ export default Vue.extend<Data, EpinioCompRecord, EpinioCompRecord, EpinioCompRe
     updateManifestConfigurations(changes: string[]) {
       this.set(this.value.configuration, { configurations: changes });
     },
+    validate(value, tab) {
```
Comment (richard-cox) [inline dashboard/pkg/epinio/edit/applications.vue:195]: As this is a typescript component these should be typed

File: dashboard/pkg/epinio/edit/applications.vue [hunk 2]
```diff
@@ -191,6 +192,13 @@ export default Vue.extend<Data, EpinioCompRecord, EpinioCompRecord, EpinioCompRe
...
+      if (tab) {
+        this.tabErrors[tab] = !value;
+      }
+
+      this.steps[0].ready = value;
```
Comment (richard-cox) [inline dashboard/pkg/epinio/edit/applications.vue:200]: The `step` `ready` property determines if the wizard can let the user go `next` to the step (user cannot progress to a step that is not `ready`). 

In the edit context where this is no wizard, the `validation-passed` property in `CruResource` should tie in to the tabErrors values

**Review by richard-cox — CHANGES_REQUESTED** [review]

File: dashboard/pkg/epinio/edit/applications.vue (hunk 2 above)
Comment (torchiaf) [reply dashboard/pkg/epinio/edit/applications.vue:204]: I've moved the validation check to tab errors, I also think it's more appropriate; note that the 'Update Source' in the tab where we use the Wizard saves settings as well, so I think we should still disable the button -  `this.steps[0].ready = false` - in case of tab errors.

Comment (richard-cox) [reply dashboard/pkg/epinio/edit/applications.vue:204]: ah, i see. It's disabling the button in the source tab... which is a wizard step, rather than control the flow of a wizard.

i think i got my statement wrong, looks like ready is specifically for the current step and whether the user can progress away from it.

**Review by richard-cox — APPROVED** [review]
